### ISSUE TITLE
Rust Installation instruction for Windows OS

### ISSUE THREAD

**Issue by dvigneshwer** [MozillaTN/Rust#3]
**Objective:** Create a markdown file listing all the common problems faced during installation of rust compiler and cargo in Windows OS

**File details:**

- [ ] List out common problems of Windows installation
- [ ] Document all the solutions with links

**Comment by rockrajesh23** [comment]
It requires C++ Build Tools for proper compiling of Rust in windows.
Link: [http://landinghub.visualstudio.com/visual-cpp-build-tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)

**Comment by dvigneshwer** [comment]
Can you make a proper markdown file with the screenshot of the error and the hack for solving it.

Ref :- [Resource Kit](https://github.com/MozillaTN/Rust/blob/master/Important_links.md)

**Comment by dvigneshwer** [comment]
https://medium.com/@saileshbaskar2/rust-installation-mainly-for-windows-b52c187146aa#.orgkw3wgb
