### ISSUE TITLE
Code snippets for explaining advantages of using Rust

### ISSUE THREAD

**Issue by SubhrajyotiSen** [MozillaTN/Rust#6]
We can have a collection of code snippets that showcase the advantages of Rust when compared to languages like C++ .

**Comment by dvigneshwer** [comment]
We will follow up these request in [ Community Rust benchmarking project](https://github.com/dvigneshwer/Benchmarking_Rust/issues)

[Slides](https://docs.google.com/presentation/d/1v32uhoZfc9yiVDBFb86r_Lk8STKtgXEtq7oJDbpLwdk/edit?usp=sharing) 3,4 and 5 cover few aspects which may interest you.
