### ISSUE TITLE
Best IDE's for Rust ?

### ISSUE THREAD

**Issue by dvigneshwer** [MozillaTN/Rust#7]
Please list the best IDE's for rust development?

**Comment by DineshMv** [comment]
@dvigneshwer Geany is one of the simplest IDE that supports Rust.

**Comment by DineshMv** [comment]
The most popular IDEs are 
VS: Code, 
InetlliJ and Eclipse.

**Comment by dvigneshwer** [comment]
Awesome list. Thanks for adding them here @DineshMv  :) 

It would be great if you can share their links too for the community members. 

Let's keep this issue alive till we get at least 10 IDE collections, post which we can have a blog about these :)

**Comment by aurabindo** [comment]
Atom works well too!

**Comment by nifey** [comment]
[https://areweideyet.com/](https://areweideyet.com/). This website has information and links of rust plugins for different IDEs and editors.

Personally, I use atom with packages like racer and rustfmt.

**Comment by amitkumarj441** [comment]
@dvigneshwer Haven't seen any file in the repo where I can list out all available rust framework/IDE for Web development.

**Comment by dvigneshwer** [comment]
@amitkumarj441 There are couple of ways by which you can add the resources,

-  Create a new header in https://github.com/MozillaTN/Rust/blob/master/Important_links.md and add all the important resources
- Secondly you can fork this repo, create a directory where you can add all the web dev related resources and give a PR

Let me know if this helps :)

**Comment by dvigneshwer** [comment]
Links updated in important_link.md file 

Closing this one.
